name: C++ CMake Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Showing cmake version
        run: |
          cmake --version

      - name: List project files
        run: find . -type f | sort
    
      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: |
          cmake --build ./build
